### PR TITLE
Use patterns/signatures to grab data from memory

### PR DESCRIPTION
**Pull request by AmyrAhmady**
This PR adds pattern scanning functionality and removes hardcoded addresses/offsets which was limiting it to SA-MP 0.3.7 R1 only, now it should theoretically work on all of them, tested it with R4 and it was working

Both AddChatMessage call and SendMessage hook are now using pattern scanning to be found on memory.

#### NOTE: I haven't tested it in your plugin yet, but it's working in my sample, I can't do testing myself right now as I don't have access to my windows machine directly, I did this PR by connecting to my laptop at home using AnyDesk, so it's a pain to do it...

### CODE REVIEW

**Comment by fl1k** [comment]
Crashes on R1.. Looking for the error

**Comment by fl1k** [comment]
DWORD dwCallAddr = *(DWORD *)(ACMAddr + 0xD) + ACMAddr + 0xD + 0x4;
		DWORD dwInfo = *(DWORD *)(ACMAddr + 0x2);

		__asm mov edx, dword ptr[dwInfo]
		__asm mov eax, [edx]
		__asm push cText
		__asm push eax
		__asm call dwCallAddr
		__asm add esp, 8

causes crashing,

**Comment by AmyrAhmady** [comment]
Don't know really why you forced pushed into this RP, but I fixed merge conflicts as well, everything should be working fine right, main.cpp is a bit changed from what you had, I added a new check on top, that's fine, you check the rest to see if anything is missing after solving merge conflicts

**Comment by fl1k** [comment]
Looks good, works on R1, dunno for other versions. I am bad at using gits, still learning..

I will merge this and make some changes, good work

**Pull request merged**
